### ISSUE TITLE
Fatal Error if plugin is active and levels page uses [pmpro_levels]

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-advanced-levels-shortcode#25]
The following error occurs on the levels page when `[pmpro_levels]` is used instead of the advanced levels shortcode and the advanced shortcode plugin is active.

[11-Jul-2018 08:08:21 UTC] PHP Fatal error:  Cannot redeclare pmpro_pages_shortcode() (previously declared in /public_html/wp-content/plugins/paid-memberships-pro/includes/init.php:138) in /public_html/wp-content/plugins/paid-memberships-pro/includes/init.php on line 138

**Comment by JarrydLong** [comment]
Tested in version 0.2.4 without any errors. pmpro_pages_shortcode is also no longer used in this version.

**Comment by ieremias-ioi** [comment]
I am using Thrive Architect and Apprentice with PaidMembershipsPro (PMP) and received the same error. I first deactivated Architect so that I could access the standard WP editor for the page that's causing the error. I then deleted all content on the page and saved it. I then added the PMP Member Levels block instead of using the corresponding PMP shortcode.  I checked my work and verified that the error was gone.
I then reactivated Architect and the error was still not present.  I then added back my Architech content (which was a fancy divider with an image). This worked well with no error message.  https://myaua.org/login-myaua/registration-fee/?preview=true
Try these steps and let me know what works!
Good luck!
Jeremiah
